services:
  doom-app:
    build: .
    image: andiikaa/doom-in-docker
    restart: always
    ports: 
        - 8080:8080
    environment:
        - BASE_PATH=/doom
    develop:
      watch:
        - action: rebuild
          path: nginx.conf.template
        - action: rebuild
          path: docker-compose.yaml
        - action: rebuild
          path: entrypoint.sh